apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: payments-dev
  namespace: kargobook-demo
spec:
  requestedFreight:
    - origin:
        kind: Warehouse
        name: payments-warehouse
      sources:
        direct: true
  promotionTemplate:
    spec:
      steps:
        - uses: git-clone
          config:
            repoURL: https://github.com/kargobook/demo-gitops.git
            checkout:
              - branch: main
                path: ./repo
        - uses: kustomize-set-image
          config:
            path: ./repo/apps/payments/envs/dev
            images:
              - image: ghcr.io/kargobook/payments-api
        - uses: git-commit
          config:
            path: ./repo
            message: "promote payments to dev: ${{ freight.image.tag }}"
        - uses: git-push
          config:
            path: ./repo
            targetBranch: main
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: payments-staging
  namespace: kargobook-demo
spec:
  requestedFreight:
    - origin:
        kind: Warehouse
        name: payments-warehouse
      sources:
        stages:
          - payments-dev
  promotionTemplate:
    spec:
      steps:
        - uses: git-clone
          config:
            repoURL: https://github.com/kargobook/demo-gitops.git
            checkout:
              - branch: main
                path: ./repo
        - uses: kustomize-set-image
          config:
            path: ./repo/apps/payments/envs/staging
            images:
              - image: ghcr.io/kargobook/payments-api
        - uses: git-commit
          config:
            path: ./repo
            message: "promote payments to staging: ${{ freight.image.tag }}"
        - uses: git-push
          config:
            path: ./repo
            targetBranch: main
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: payments-prod
  namespace: kargobook-demo
spec:
  requestedFreight:
    - origin:
        kind: Warehouse
        name: payments-warehouse
      sources:
        stages:
          - payments-staging
  promotionTemplate:
    spec:
      steps:
        - uses: git-clone
          config:
            repoURL: https://github.com/kargobook/demo-gitops.git
            checkout:
              - branch: main
                path: ./repo
        - uses: kustomize-set-image
          config:
            path: ./repo/apps/payments/envs/prod
            images:
              - image: ghcr.io/kargobook/payments-api
        - uses: git-commit
          config:
            path: ./repo
            message: "promote payments to prod: ${{ freight.image.tag }}"
        - uses: git-push
          config:
            path: ./repo
            targetBranch: main
