apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: staging
  namespace: demo
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: demo-app
    sources:
      stages:
      - dev
  promotionTemplate:
    spec:
      vars:
        - name: gitRepo
          value: https://github.com/kargobook/demo-gitops.git
      steps:
      - uses: git-clone
        config:
          repoURL: ${{ vars.gitRepo }}
          checkout:
          - branch: main
            path: ./repo
      - uses: kustomize-set-image
        config:
          path: ./repo/envs/staging
          images:
          - image: ghcr.io/kargobook/demo-app
            tag: ${{ imageFrom("ghcr.io/kargobook/demo-app").Tag }}
      - uses: git-commit
        as: commit
        config:
          path: ./repo
          message: 'Promote to staging: ${{ imageFrom("ghcr.io/kargobook/demo-app").Tag }}'
      - uses: git-push
        config:
          path: ./repo
          targetBranch: main
      - uses: argocd-update
        config:
          apps:
          - name: demo-staging
            sources:
            - repoURL: ${{ vars.gitRepo }}
